export const productsData = {
    food: [
      { id: 1, image: "https://via.placeholder.com/150?text=Apple", name: "Organic Apples (1kg)", description: "Fresh, crisp, and sweet organic apples.", shippingFee: "$3", price: "$5", rating: 4 },
      { id: 2, image: "https://via.placeholder.com/150?text=Banana", name: "Bananas (1 bunch)", description: "Ripe bananas perfect for smoothies.", shippingFee: "$3", price: "$4", rating: 5 },
      { id: 3, image: "https://via.placeholder.com/150?text=Bread", name: "Whole Wheat Bread", description: "Freshly baked whole wheat bread.", shippingFee: "$2", price: "$3", rating: 4 },
      { id: 4, image: "https://via.placeholder.com/150?text=Cheese", name: "Cheddar Cheese (200g)", description: "Aged cheddar cheese with sharp flavor.", shippingFee: "$2", price: "$6", rating: 4 },
      { id: 5, image: "https://via.placeholder.com/150?text=Yogurt", name: "Greek Yogurt (500g)", description: "Creamy Greek yogurt packed with protein.", shippingFee: "$2", price: "$5", rating: 5 },
      { id: 6, image: "https://via.placeholder.com/150?text=Chicken", name: "Organic Chicken Breast (1kg)", description: "Free-range organic chicken breast.", shippingFee: "$5", price: "$12", rating: 4 },
      { id: 7, image: "https://via.placeholder.com/150?text=Salmon", name: "Fresh Salmon Fillets (500g)", description: "Wild-caught salmon fillets.", shippingFee: "$6", price: "$18", rating: 5 },
      { id: 8, image: "https://via.placeholder.com/150?text=Rice", name: "Organic Brown Rice (1kg)", description: "Healthy and nutritious organic brown rice.", shippingFee: "$3", price: "$4", rating: 4 },
      { id: 9, image: "https://via.placeholder.com/150?text=Spinach", name: "Fresh Spinach (300g)", description: "Tender and fresh spinach leaves.", shippingFee: "$2", price: "$3", rating: 5 },
      { id: 10, image: "https://via.placeholder.com/150?text=Tomatoes", name: "Roma Tomatoes (500g)", description: "Vibrant and juicy Roma tomatoes.", shippingFee: "$2", price: "$4", rating: 4 },
      { id: 11, image: "https://via.placeholder.com/150?text=Orange", name: "Citrus Oranges (1kg)", description: "Sweet and tangy fresh oranges.", shippingFee: "$3", price: "$5", rating: 4 },
      { id: 12, image: "https://via.placeholder.com/150?text=Grapes", name: "Seedless Grapes (500g)", description: "Sweet and refreshing seedless grapes.", shippingFee: "$3", price: "$6", rating: 5 },
      { id: 13, image: "https://via.placeholder.com/150?text=Oats", name: "Organic Rolled Oats (1kg)", description: "Healthy organic oats for a great breakfast.", shippingFee: "$3", price: "$4", rating: 4 },
      { id: 14, image: "https://via.placeholder.com/150?text=Avocado", name: "Organic Avocados (2 pieces)", description: "Creamy organic avocados.", shippingFee: "$3", price: "$7", rating: 5 },
      { id: 15, image: "https://via.placeholder.com/150?text=Olive+Oil", name: "Extra Virgin Olive Oil (500ml)", description: "Premium extra virgin olive oil for cooking and dressing.", shippingFee: "$4", price: "$8", rating: 5 },
      { id: 16, image: "https://via.placeholder.com/150?text=Almonds", name: "Roasted Almonds (250g)", description: "Crunchy and flavorful roasted almonds.", shippingFee: "$3", price: "$5", rating: 4 },
      { id: 17, image: "https://via.placeholder.com/150?text=Milk", name: "Organic Whole Milk (1L)", description: "Rich and creamy organic milk.", shippingFee: "$2", price: "$3", rating: 5 },
      { id: 18, image: "https://via.placeholder.com/150?text=Honey", name: "Raw Honey (500g)", description: "Pure raw honey harvested from local hives.", shippingFee: "$3", price: "$8", rating: 5 },
      { id: 19, image: "https://via.placeholder.com/150?text=Potato", name: "Fresh Potatoes (2kg)", description: "Versatile fresh potatoes.", shippingFee: "$4", price: "$5", rating: 4 },
      { id: 20, image: "https://via.placeholder.com/150?text=Carrot", name: "Fresh Carrots (500g)", description: "Crunchy and sweet fresh carrots.", shippingFee: "$2", price: "$2", rating: 5 }
    ],
  
    electronics: [
      { id: 21, image: "https://via.placeholder.com/150?text=Smartphone", name: "Apple iPhone 14 Pro Max", description: "Latest Apple smartphone with 5G and 512GB storage.", shippingFee: "$5", price: "$1,099", rating: 5 },
      { id: 22, image: "https://via.placeholder.com/150?text=Laptop", name: "MacBook Pro 16-inch", description: "Powerful 16-inch laptop with M1 Pro chip, 16GB RAM, 1TB SSD.", shippingFee: "$10", price: "$2,399", rating: 5 },
      { id: 23, image: "https://via.placeholder.com/150?text=Smartwatch", name: "Apple Watch Series 7", description: "Advanced smartwatch with fitness tracking, GPS, and ECG.", shippingFee: "$4", price: "$399", rating: 5 },
      { id: 24, image: "https://via.placeholder.com/150?text=Tablet", name: "Samsung Galaxy Tab S7", description: "10.5-inch tablet with Snapdragon 865+, S Pen, and 6GB RAM.", shippingFee: "$5", price: "$649", rating: 4 },
      { id: 25, image: "https://via.placeholder.com/150?text=Camera", name: "Sony Alpha 7 III Mirrorless Camera", description: "Full-frame mirrorless camera with 24.2MP sensor and 4K video recording.", shippingFee: "$12", price: "$1,998", rating: 5 },
      { id: 26, image: "https://via.placeholder.com/150?text=Headphones", name: "Sony WH-1000XM4", description: "Wireless noise-canceling headphones with 30-hour battery life.", shippingFee: "$4", price: "$349", rating: 5 },
      { id: 27, image: "https://via.placeholder.com/150?text=Smart+TV", name: "LG OLED C1 55-inch 4K Smart TV", description: "OLED display with 4K resolution and Dolby Vision.", shippingFee: "$15", price: "$1,499", rating: 5 },
      { id: 28, image: "https://via.placeholder.com/150?text=Projector", name: "Epson Home Cinema 3800 4K Projector", description: "4K UHD projector with advanced image processing for home theater.", shippingFee: "$20", price: "$1,699", rating: 4 },
      { id: 29, image: "https://via.placeholder.com/150?text=Printer", name: "HP LaserJet Pro MFP M428fdw", description: "Wireless monochrome laser printer with duplex printing.", shippingFee: "$8", price: "$249", rating: 4 },
      { id: 210, image: "https://via.placeholder.com/150?text=Speaker", name: "Sonos One (Gen 2) Smart Speaker", description: "Compact speaker with voice control and rich sound.", shippingFee: "$5", price: "$199", rating: 5 },
      { id: 211, image: "https://via.placeholder.com/150?text=Router", name: "Netgear Nighthawk AX12 WiFi 6 Router", description: "WiFi 6 router with 12-stream performance for gaming and streaming.", shippingFee: "$6", price: "$399", rating: 4 },
      { id: 122, image: "https://via.placeholder.com/150?text=Drone", name: "DJI Mavic Air 2 Drone", description: "Compact drone with 48MP camera and 4K video.", shippingFee: "$12", price: "$799", rating: 5 },
      { id: 132, image: "https://via.placeholder.com/150?text=Monitor", name: "Dell UltraSharp U2720Q 27-inch 4K Monitor", description: "27-inch 4K monitor with USB-C connectivity and color accuracy.", shippingFee: "$15", price: "$639", rating: 4 },
      { id: 142, image: "https://via.placeholder.com/150?text=Smart+Lock", name: "August Wi-Fi Smart Lock", description: "Smart lock with remote control and voice assistant compatibility.", shippingFee: "$6", price: "$229", rating: 5 },
      { id: 215, image: "https://via.placeholder.com/150?text=External+Hard+Drive", name: "Seagate Backup Plus Portable 2TB", description: "Portable external hard drive with 2TB storage for backups.", shippingFee: "$5", price: "$69", rating: 4 },
      { id: 316, image: "https://via.placeholder.com/150?text=Keyboard", name: "Logitech MX Keys Wireless Keyboard", description: "Wireless keyboard with backlighting and USB-C charging.", shippingFee: "$5", price: "$99", rating: 5 },
      { id: 137, image: "https://via.placeholder.com/150?text=Smart+Bulb", name: "Philips Hue White and Color Ambiance A19", description: "Smart LED bulb with color changing and app control.", shippingFee: "$4", price: "$49", rating: 5 },
      { id: 318, image: "https://via.placeholder.com/150?text=Camera", name: "Canon EOS Rebel T7 DSLR Camera", description: "Affordable DSLR camera with 24.1MP, Wi-Fi, and Full HD video.", shippingFee: "$10", price: "$549", rating: 4 },
      { id: 149, image: "https://via.placeholder.com/150?text=Microwave", name: "Panasonic 1.6 Cu. Ft. Countertop Microwave", description: "Countertop microwave with 1000W of power and inverter technology.", shippingFee: "$12", price: "$249", rating: 4 },
      { id: 230, image: "https://via.placeholder.com/150?text=Smart+Speaker", name: "Amazon Echo Dot (4th Gen)", description: "Smart speaker with Alexa for music and voice commands.", shippingFee: "$3", price: "$49", rating: 5 }
    ],
  
    clothing: [
      { id: 31, image: "https://via.placeholder.com/150?text=Jeans", name: "Levi's 501 Original Fit Jeans", description: "Classic denim jeans with regular fit.", shippingFee: "$4", price: "$59", rating: 5 },
      { id: 32, image: "https://via.placeholder.com/150?text=T-shirt", name: "Nike Air T-shirt", description: "Comfortable cotton t-shirt with Nike Air logo.", shippingFee: "$3", price: "$30", rating: 4 },
      { id: 33, image: "https://via.placeholder.com/150?text=Jacket", name: "North Face Fleece Jacket", description: "Warm fleece jacket for cold weather.", shippingFee: "$5", price: "$99", rating: 4 },
      { id: 34, image: "https://via.placeholder.com/150?text=Sweater", name: "Uniqlo Merino Wool Sweater", description: "Soft and lightweight merino wool sweater.", shippingFee: "$4", price: "$49", rating: 5 },
      { id: 35, image: "https://via.placeholder.com/150?text=Shoes", name: "Adidas UltraBoost Sneakers", description: "Comfortable running shoes with responsive cushioning.", shippingFee: "$5", price: "$120", rating: 4 },
      { id: 36, image: "https://via.placeholder.com/150?text=Shorts", name: "Under Armour Tech 2.0 Shorts", description: "Quick-drying athletic shorts for running and gym.", shippingFee: "$3", price: "$24.99", rating: 5 },
      { id: 37, image: "https://via.placeholder.com/150?text=Jacket", name: "Patagonia Nano Puff Jacket", description: "Packable, insulated jacket for outdoor activities.", shippingFee: "$6", price: "$199", rating: 5 },
      { id: 38, image: "https://via.placeholder.com/150?text=Dress", name: "H&M Sleeveless Dress", description: "Casual sleeveless dress for summer wear.", shippingFee: "$4", price: "$39.99", rating: 4 },
      { id: 39, image: "https://via.placeholder.com/150?text=Hoodie", name: "Champion Reverse Weave Hoodie", description: "Classic pullover hoodie with a comfortable fit.", shippingFee: "$5", price: "$55", rating: 5 },
      { id: 310, image: "https://via.placeholder.com/150?text=Blouse", name: "Zara Satin Blouse", description: "Elegant satin blouse for formal or casual events.", shippingFee: "$4", price: "$29.99", rating: 4 },
      { id: 311, image: "https://via.placeholder.com/150?text=Shoes", name: "Vans Old Skool Sneakers", description: "Classic skate shoes with durable canvas and leather.", shippingFee: "Free", price: "$65", rating: 4 },
      { id: 312, image: "https://via.placeholder.com/150?text=Suit", name: "Hugo Boss Slim Fit Suit", description: "Tailored slim fit suit for professional settings.", shippingFee: "$8", price: "$799", rating: 5 },
      { id: 313, image: "https://via.placeholder.com/150?text=Hat", name: "Adidas Originals Baseball Cap", description: "Classic 6-panel cap with embroidered logo.", shippingFee: "$3", price: "$25", rating: 4 },
      { id: 314, image: "https://via.placeholder.com/150?text=Scarf", name: "Burberry Cashmere Scarf", description: "Luxurious cashmere scarf with signature Burberry pattern.", shippingFee: "$7", price: "$350", rating: 5 },
      { id: 315, image: "https://via.placeholder.com/150?text=Bag", name: "Michael Kors Jet Set Travel Tote", description: "Stylish tote bag with gold-tone hardware.", shippingFee: "$6", price: "$298", rating: 4 },
      { id: 316, image: "https://via.placeholder.com/150?text=Boots", name: "Timberland PRO Work Boots", description: "Durable work boots with slip-resistant sole and waterproof features.", shippingFee: "$7", price: "$170", rating: 5 },
      { id: 317, image: "https://via.placeholder.com/150?text=Gloves", name: "North Face Etip Gloves", description: "Touchscreen-compatible gloves for cold weather.", shippingFee: "$4", price: "$45", rating: 4 },
      { id: 318, image: "https://via.placeholder.com/150?text=Shirt", name: "Calvin Klein Dress Shirt", description: "Wrinkle-resistant dress shirt for work or formal occasions.", shippingFee: "$4", price: "$79", rating: 5 },
      { id: 319, image: "https://via.placeholder.com/150?text=Leggings", name: "Lululemon Align Leggings", description: "Comfortable and stretchy leggings for yoga and workouts.", shippingFee: "$4", price: "$98", rating: 5 },
      { id: 320, image: "https://via.placeholder.com/150?text=Coat", name: "Columbia Whirlibird IV 3-in-1 Jacket", description: "Waterproof, breathable jacket for outdoor adventures.", shippingFee: "$6", price: "$220", rating: 4 }
    ],
  
    home_appliances: [
      { id: 41, image: "https://via.placeholder.com/150?text=Refrigerator", name: "Samsung French Door Refrigerator", description: "Large 3-door fridge with ice maker and water dispenser.", shippingFee: "$20", price: "$1,299", rating: 5 },
      { id: 42, image: "https://via.placeholder.com/150?text=Washer", name: "LG Front Load Washer", description: "Energy-efficient front load washer with 4.5 cu. ft. capacity.", shippingFee: "$15", price: "$799", rating: 5 },
      { id: 43, image: "https://via.placeholder.com/150?text=Dishwasher", name: "Bosch 800 Series Dishwasher", description: "Quiet, energy-efficient dishwasher with stainless steel tub.", shippingFee: "$12", price: "$899", rating: 4 },
      { id: 44, image: "https://via.placeholder.com/150?text=Microwave", name: "Panasonic Inverter Microwave", description: "1.6 cu. ft. microwave with inverter cooking technology.", shippingFee: "$10", price: "$129", rating: 4 },
      { id: 45, image: "https://via.placeholder.com/150?text=Vacuum", name: "Dyson V11 Torque Drive Cordless Vacuum", description: "Powerful cordless vacuum with up to 60 minutes of run time.", shippingFee: "$15", price: "$699", rating: 5 },
      { id: 46, image: "https://via.placeholder.com/150?text=Air+Purifier", name: "Honeywell HPA300 Air Purifier", description: "Air purifier with HEPA filters for large rooms.", shippingFee: "$12", price: "$249", rating: 5 },
      { id: 47, image: "https://via.placeholder.com/150?text=Blender", name: "Ninja Professional Blender", description: "Powerful 1000-watt blender with 72 oz. pitcher.", shippingFee: "$7", price: "$99", rating: 4 },
      { id: 48, image: "https://via.placeholder.com/150?text=Coffee+Maker", name: "Keurig K-Elite Coffee Maker", description: "Single-serve coffee maker with iced coffee function.", shippingFee: "$5", price: "$149", rating: 4 },
      { id: 49, image: "https://via.placeholder.com/150?text=Cooktop", name: "GE 30-Inch Electric Cooktop", description: "4-burner electric cooktop with touch controls.", shippingFee: "$18", price: "$599", rating: 4 },
      { id: 1440, image: "https://via.placeholder.com/150?text=Dehumidifier", name: "Frigidaire 70-Pint Dehumidifier", description: "Dehumidifier for large rooms with continuous drain option.", shippingFee: "$15", price: "$199", rating: 5 },
      { id: 141, image: "https://via.placeholder.com/150?text=Heater", name: "Lasko Ceramic Tower Heater", description: "Portable ceramic heater with oscillation for even heating.", shippingFee: "$8", price: "$49", rating: 4 },
      { id: 142, image: "https://via.placeholder.com/150?text=Iron", name: "Rowenta DW5080 Steam Iron", description: "High-performance steam iron with stainless steel soleplate.", shippingFee: "$5", price: "$99", rating: 5 },
      { id: 143, image: "https://via.placeholder.com/150?text=Toaster", name: "Cuisinart 4-Slice Toaster", description: "4-slice toaster with multiple shade settings.", shippingFee: "$7", price: "$59", rating: 4 },
      { id: 144, image: "https://via.placeholder.com/150?text=Refrigerator", name: "Whirlpool 19-cu.ft. Refrigerator", description: "Stainless steel fridge with adjustable shelves and door bins.", shippingFee: "$20", price: "$749", rating: 4 },
      { id: 145, image: "https://via.placeholder.com/150?text=Washer", name: "Maytag Top Load Washer", description: "Energy-efficient washer with 4.7 cu. ft. capacity.", shippingFee: "$15", price: "$649", rating: 4 },
      { id: 146, image: "https://via.placeholder.com/150?text=Dryer", name: "Whirlpool Electric Dryer", description: "High-efficiency electric dryer with 7.4 cu. ft. capacity.", shippingFee: "$12", price: "$599", rating: 4 },
      { id: 147, image: "https://via.placeholder.com/150?text=Stand+Mixer", name: "KitchenAid Artisan Stand Mixer", description: "Iconic stand mixer with 10-speed settings and 5-quart bowl.", shippingFee: "$15", price: "$379", rating: 5 },
      { id: 148, image: "https://via.placeholder.com/150?text=Ice+Maker", name: "Igloo Countertop Ice Maker", description: "Portable ice maker that produces up to 26 lbs. of ice per day.", shippingFee: "$7", price: "$169", rating: 4 },
      { id: 149, image: "https://via.placeholder.com/150?text=Freezer", name: "GE 5.0-cu. ft. Chest Freezer", description: "Compact chest freezer with energy-efficient design.", shippingFee: "$20", price: "$239", rating: 5 },
      { id: 240, image: "https://via.placeholder.com/150?text=Slow+Cooker", name: "Crock-Pot 6-Quart Slow Cooker", description: "Programmable slow cooker with digital controls.", shippingFee: "$6", price: "$39", rating: 5 }
    ],
  


        sports: [
          { id: 51, image: "https://via.placeholder.com/150?text=Tennis+Racket", name: "Wilson Pro Staff Tennis Racket", description: "High-performance tennis racket for advanced players.", shippingFee: "$5", price: "$199", rating: 5 },
          { id: 52, image: "https://via.placeholder.com/150?text=Yoga+Mat", name: "Liforme Yoga Mat", description: "Eco-friendly, non-slip yoga mat for comfort and durability.", shippingFee: "$4", price: "$79", rating: 4 },
          { id: 53, image: "https://via.placeholder.com/150?text=Soccer+Ball", name: "Adidas Tango Rosario Soccer Ball", description: "Official size and weight soccer ball for practice and games.", shippingFee: "$5", price: "$35", rating: 4 },
          { id: 54, image: "https://via.placeholder.com/150?text=Baseball+Glove", name: "Rawlings Heart of the Hide Baseball Glove", description: "Premium leather glove for serious baseball players.", shippingFee: "$7", price: "$249", rating: 5 },
          { id: 55, image: "https://via.placeholder.com/150?text=Basketball", name: "Spalding NBA Street Basketball", description: "Durable outdoor basketball for street and park games.", shippingFee: "$5", price: "$29", rating: 4 },
          { id: 56, image: "https://via.placeholder.com/150?text=Golf+Clubs", name: "Callaway Strata Golf Club Set", description: "Complete 12-piece golf club set with driver, irons, and putter.", shippingFee: "$20", price: "$299", rating: 5 },
          { id: 57, image: "https://via.placeholder.com/150?text=Running+Shoes", name: "Nike Air Zoom Pegasus 38", description: "Comfortable running shoes with responsive cushioning and support.", shippingFee: "$5", price: "$120", rating: 5 },
          { id: 58, image: "https://via.placeholder.com/150?text=Cycling+Helmet", name: "Giro Savant MIPS Cycling Helmet", description: "Lightweight cycling helmet with MIPS for added safety.", shippingFee: "$6", price: "$89", rating: 4 },
          { id: 59, image: "https://via.placeholder.com/150?text=Football", name: "Wilson NFL Game Football", description: "Official NFL football used in professional games.", shippingFee: "$5", price: "$99", rating: 4 },
          { id: 150, image: "https://via.placeholder.com/150?text=Tennis+Shoes", name: "Asics Gel Resolution 8 Tennis Shoes", description: "Supportive and durable tennis shoes for serious players.", shippingFee: "$6", price: "$140", rating: 4 },
          { id: 151, image: "https://via.placeholder.com/150?text=Swimming+Goggles", name: "Speedo Vanquisher 2.0 Swimming Goggles", description: "Comfortable and leak-proof swimming goggles for competitive swimmers.", shippingFee: "$3", price: "$22", rating: 5 },
          { id: 152, image: "https://via.placeholder.com/150?text=Boxing+Gloves", name: "Everlast Pro Style Boxing Gloves", description: "Durable boxing gloves for training and sparring.", shippingFee: "$5", price: "$39", rating: 4 },
          { id: 153, image: "https://via.placeholder.com/150?text=Hiking+Boots", name: "Columbia Newton Ridge Plus Hiking Boots", description: "Waterproof hiking boots for tough terrains and long treks.", shippingFee: "$10", price: "$110", rating: 5 },
          { id: 1554, image: "https://via.placeholder.com/150?text=Jump+Rope", name: "RPM Speed Rope", description: "High-speed jump rope for fitness and conditioning.", shippingFee: "$3", price: "$20", rating: 4 },
          { id: 155, image: "https://via.placeholder.com/150?text=Exercise+Bike", name: "Schwinn 270 Recumbent Exercise Bike", description: "Recumbent bike with 25 resistance levels and built-in workout programs.", shippingFee: "$40", price: "$499", rating: 5 },
          { id: 156, image: "https://via.placeholder.com/150?text=Skateboard", name: "Santa Cruz Skateboard Complete", description: "Complete skateboard with premium components and a colorful design.", shippingFee: "$8", price: "$89", rating: 4 },
          { id: 157, image: "https://via.placeholder.com/150?text=Tennis+Shoes", name: "Adidas Barricade 2019 Tennis Shoes", description: "Performance-oriented tennis shoes for stability and comfort.", shippingFee: "$6", price: "$100", rating: 4 },
          { id: 158, image: "https://via.placeholder.com/150?text=Weight+Set", name: "Bowflex SelectTech 552 Adjustable Dumbbells", description: "Adjustable dumbbell set with weight range from 5 to 52.5 lbs.", shippingFee: "$15", price: "$299", rating: 5 },
          { id: 159, image: "https://via.placeholder.com/150?text=Soccer+Cleave", name: "Nike Vapor Grip3 Soccer Cleats", description: "Lightweight and responsive cleats designed for soccer players.", shippingFee: "$6", price: "$140", rating: 4 },
          { id: 250, image: "https://via.placeholder.com/150?text=Weight+Lifting+Gloves", name: "Harbinger Power Weight Lifting Gloves", description: "Comfortable gloves for enhanced grip during weightlifting.", shippingFee: "$3", price: "$25", rating: 4 }
        ],
      
        beauty: [
          { id: 61, image: "https://via.placeholder.com/150?text=Foundation", name: "Fenty Beauty Pro Filt'r Foundation", description: "Full-coverage foundation for a flawless finish.", shippingFee: "$4", price: "$36", rating: 5 },
          { id: 62, image: "https://via.placeholder.com/150?text=Skincare", name: "CeraVe Hydrating Facial Cleanser", description: "Gentle, non-foaming facial cleanser for dry skin.", shippingFee: "$3", price: "$14", rating: 4 },
          { id: 63, image: "https://via.placeholder.com/150?text=Shampoo", name: "Pureology Hydrate Shampoo", description: "Moisturizing shampoo for dry and color-treated hair.", shippingFee: "$4", price: "$32", rating: 4 },
          { id: 64, image: "https://via.placeholder.com/150?text=Lipstick", name: "MAC Retro Matte Lipstick", description: "Long-wearing matte lipstick in a variety of shades.", shippingFee: "$3", price: "$21", rating: 5 },
          { id: 65, image: "https://via.placeholder.com/150?text=Eyeliner", name: "Urban Decay 24/7 Glide-On Eye Pencil", description: "Creamy, long-lasting eyeliner pencil with intense color payoff.", shippingFee: "$3", price: "$22", rating: 5 },
          { id: 66, image: "https://via.placeholder.com/150?text=Moisturizer", name: "Neutrogena Hydro Boost Water Gel", description: "Oil-free gel moisturizer for hydrated and glowing skin.", shippingFee: "$3", price: "$18", rating: 4 },
          { id: 67, image: "https://via.placeholder.com/150?text=Face+Mask", name: "Aztec Secret Indian Healing Clay", description: "Deep pore cleansing mask for detoxifying and clarifying.", shippingFee: "$4", price: "$10", rating: 5 },
          { id: 68, image: "https://via.placeholder.com/150?text=Perfume", name: "Chanel No. 5 Eau de Parfum", description: "Timeless fragrance with floral and woody notes.", shippingFee: "$5", price: "$130", rating: 5 },
          { id: 69, image: "https://via.placeholder.com/150?text=Hair+Dryer", name: "Dyson Supersonic Hair Dryer", description: "High-performance hair dryer with intelligent heat control.", shippingFee: "$8", price: "$399", rating: 5 },
          { id: 160, image: "https://via.placeholder.com/150?text=Face+Serum", name: "The Ordinary Niacinamide 10% + Zinc 1%", description: "Brightening and pore-reducing serum for smoother skin.", shippingFee: "$3", price: "$6", rating: 4 },
          { id: 161, image: "https://via.placeholder.com/150?text=Lip+Balm", name: "Burt's Bees Beeswax Lip Balm", description: "Nourishing lip balm with natural beeswax and vitamin E.", shippingFee: "$2", price: "$4", rating: 4 },
          { id: 162, image: "https://via.placeholder.com/150?text=Face+Toner", name: "Thayers Witch Hazel Toner", description: "Alcohol-free facial toner with witch hazel for refreshed skin.", shippingFee: "$3", price: "$11", rating: 5 },
          { id: 163, image: "https://via.placeholder.com/150?text=Nail+Polish", name: "OPI Nail Lacquer", description: "Long-lasting, chip-resistant nail polish in various shades.", shippingFee: "$3", price: "$9", rating: 4 },
          { id: 164, image: "https://via.placeholder.com/150?text=Shaving+Razor", name: "Gillette Fusion ProGlide Razor", description: "Precision razor for a smooth and close shave.", shippingFee: "$2", price: "$15", rating: 4 },
          { id: 165, image: "https://via.placeholder.com/150?text=Makeup+Brush", name: "Real Techniques Makeup Brushes", description: "High-quality brushes for flawless makeup application.", shippingFee: "$3", price: "$25", rating: 5 },
          { id: 166, image: "https://via.placeholder.com/150?text=Hair+Mask", name: "Olaplex Hair Perfector No. 3", description: "Bond-building treatment for stronger and healthier hair.", shippingFee: "$5", price: "$28", rating: 5 },
          { id: 167, image: "https://via.placeholder.com/150?text=Body+Lotion", name: "Aveeno Daily Moisturizing Lotion", description: "Non-greasy, fast-absorbing lotion for soft, hydrated skin.", shippingFee: "$3", price: "$7", rating: 4 },
          { id: 168, image: "https://via.placeholder.com/150?text=Makeup+Remover", name: "Clinique Take The Day Off Makeup Remover", description: "Gentle makeup remover that dissolves makeup without irritating.", shippingFee: "$3", price: "$19", rating: 4 },
          { id: 169, image: "https://via.placeholder.com/150?text=Shampoo", name: "Moroccanoil Hydrating Shampoo", description: "Moisturizing shampoo with argan oil for smooth hair.", shippingFee: "$5", price: "$24", rating: 5 },
          { id: 260, image: "https://via.placeholder.com/150?text=Bronzer", name: "NARS Laguna Bronzer", description: "Sunkissed bronzer with a subtle shimmer for a natural glow.", shippingFee: "$3", price: "$40", rating: 5 }
        ],
      
        books: [
          { id: 71, image: "https://via.placeholder.com/150?text=Book1", name: "The Great Gatsby", description: "A classic novel by F. Scott Fitzgerald about the American Dream.", shippingFee: "$3", price: "$10", rating: 5 },
          { id: 72, image: "https://via.placeholder.com/150?text=Book2", name: "1984", description: "George Orwell's dystopian novel about a totalitarian regime.", shippingFee: "$3", price: "$12", rating: 5 },
          { id: 73, image: "https://via.placeholder.com/150?text=Book3", name: "To Kill a Mockingbird", description: "Harper Lee's Pulitzer Prize-winning novel about racial injustice.", shippingFee: "$3", price: "$15", rating: 5 },
          { id: 74, image: "https://via.placeholder.com/150?text=Book4", name: "Pride and Prejudice", description: "Jane Austen's beloved romantic novel of manners and marriage.", shippingFee: "$3", price: "$9", rating: 4 },
          { id: 75, image: "https://via.placeholder.com/150?text=Book5", name: "The Catcher in the Rye", description: "J.D. Salinger's story of an alienated teen in New York City.", shippingFee: "$3", price: "$13", rating: 4 },
          { id: 76, image: "https://via.placeholder.com/150?text=Book6", name: "The Hobbit", description: "J.R.R. Tolkien's epic fantasy novel about Bilbo Baggins.", shippingFee: "$3", price: "$10", rating: 5 },
          { id: 77, image: "https://via.placeholder.com/150?text=Book7", name: "The Lord of the Rings", description: "J.R.R. Tolkien's epic high fantasy trilogy.", shippingFee: "$3", price: "$25", rating: 5 },
          { id: 78, image: "https://via.placeholder.com/150?text=Book8", name: "The Alchemist", description: "Paulo Coelho's story about following one's dreams.", shippingFee: "$3", price: "$14", rating: 4 },
          { id: 79, image: "https://via.placeholder.com/150?text=Book9", name: "Harry Potter and the Sorcerer's Stone", description: "The first book in J.K. Rowling's magical series.", shippingFee: "$4", price: "$18", rating: 5 },
          { id: 170, image: "https://via.placeholder.com/150?text=Book10", name: "Moby Dick", description: "Herman Melville's epic tale of a sailor's obsession with a whale.", shippingFee: "$3", price: "$17", rating: 4 },
          { id: 171, image: "https://via.placeholder.com/150?text=Book11", name: "The Odyssey", description: "Homer's ancient Greek epic poem about Odysseus' adventures.", shippingFee: "$3", price: "$14", rating: 4 },
          { id: 172, image: "https://via.placeholder.com/150?text=Book12", name: "Brave New World", description: "Aldous Huxley's futuristic novel about a totalitarian society.", shippingFee: "$3", price: "$12", rating: 5 },
          { id: 173, image: "https://via.placeholder.com/150?text=Book13", name: "Crime and Punishment", description: "Fyodor Dostoevsky's psychological thriller about morality and guilt.", shippingFee: "$3", price: "$16", rating: 4 },
          { id: 174, image: "https://via.placeholder.com/150?text=Book14", name: "War and Peace", description: "Leo Tolstoy's epic historical novel set during the Napoleonic wars.", shippingFee: "$3", price: "$20", rating: 5 },
          { id: 175, image: "https://via.placeholder.com/150?text=Book15", name: "Anna Karenina", description: "Leo Tolstoy's tragic love story of a married aristocrat.", shippingFee: "$3", price: "$18", rating: 5 },
          { id: 176, image: "https://via.placeholder.com/150?text=Book16", name: "The Sun Also Rises", description: "Ernest Hemingway's story of disillusionment after WWI.", shippingFee: "$3", price: "$11", rating: 4 },
          { id: 177, image: "https://via.placeholder.com/150?text=Book17", name: "The Picture of Dorian Gray", description: "Oscar Wilde's novel about vanity and moral corruption.", shippingFee: "$3", price: "$13", rating: 5 },
          { id: 178, image: "https://via.placeholder.com/150?text=Book18", name: "Frankenstein", description: "Mary Shelley's tale of a scientist and his monstrous creation.", shippingFee: "$3", price: "$10", rating: 4 },
          { id: 179, image: "https://via.placeholder.com/150?text=Book19", name: "Dracula", description: "Bram Stoker's gothic novel about the infamous vampire.", shippingFee: "$3", price: "$12", rating: 5 },
          { id: 270, image: "https://via.placeholder.com/150?text=Book20", name: "The Brothers Karamazov", description: "Fyodor Dostoevsky's exploration of faith, doubt, and family.", shippingFee: "$3", price: "$19", rating: 5 }
        ],
      
        toys: [
          { id: 81, image: "https://via.placeholder.com/150?text=Toy1", name: "LEGO Star Wars Millennium Falcon", description: "Build the iconic Millennium Falcon with over 1300 pieces.", shippingFee: "$8", price: "$160", rating: 5 },
          { id: 82, image: "https://via.placeholder.com/150?text=Toy2", name: "Barbie Dreamhouse", description: "A luxurious 3-story dollhouse for endless imaginative play.", shippingFee: "$12", price: "$199", rating: 5 },
          { id: 83, image: "https://via.placeholder.com/150?text=Toy3", name: "Hot Wheels Race Track Set", description: "A thrilling race track set with loops and ramps for Hot Wheels cars.", shippingFee: "$6", price: "$45", rating: 4 },
          { id: 84, image: "https://via.placeholder.com/150?text=Toy4", name: "Nerf N-Strike Elite Blaster", description: "High-performance dart blaster with rapid-fire action.", shippingFee: "$5", price: "$30", rating: 4 },
          { id: 85, image: "https://via.placeholder.com/150?text=Toy5", name: "Play-Doh Fun Factory", description: "Create endless shapes and figures with Play-Doh.", shippingFee: "$3", price: "$19", rating: 5 },
          { id: 86, image: "https://via.placeholder.com/150?text=Toy6", name: "Fisher-Price Little People Farm Set", description: "Interactive farm playset with figures and animals.", shippingFee: "$5", price: "$40", rating: 4 },
          { id: 87, image: "https://via.placeholder.com/150?text=Toy7", name: "Disney Princess Doll Set", description: "Collectible dolls featuring favorite Disney Princesses.", shippingFee: "$5", price: "$60", rating: 5 },
          { id: 88, image: "https://via.placeholder.com/150?text=Toy8", name: "Transformers Optimus Prime Action Figure", description: "Poseable action figure of the leader of the Autobots.", shippingFee: "$6", price: "$40", rating: 5 },
          { id: 89, image: "https://via.placeholder.com/150?text=Toy9", name: "VTech Go! Go! Smart Wheels", description: "Interactive toy vehicles that play sounds and songs.", shippingFee: "$4", price: "$25", rating: 4 },
          { id: 180, image: "https://via.placeholder.com/150?text=Toy10", name: "American Girl Doll", description: "A beautiful doll that represents different historical periods.", shippingFee: "$6", price: "$100", rating: 5 },
          { id: 181, image: "https://via.placeholder.com/150?text=Toy11", name: "Mega Bloks First Builders Set", description: "Colorful building blocks for toddlers and young children.", shippingFee: "$4", price: "$15", rating: 5 },
          { id: 182, image: "https://via.placeholder.com/150?text=Toy12", name: "Hatchimals CollEGGtibles", description: "Surprise egg toys that reveal a collectible figure inside.", shippingFee: "$3", price: "$12", rating: 4 },
          { id: 183, image: "https://via.placeholder.com/150?text=Toy13", name: "FurReal Friends Interactive Pet", description: "An interactive pet that responds to touch and sounds.", shippingFee: "$5", price: "$70", rating: 4 },
          { id: 184, image: "https://via.placeholder.com/150?text=Toy14", name: "RC Helicopter", description: "Remote-controlled helicopter with 3-channel flight control.", shippingFee: "$7", price: "$50", rating: 4 },
          { id: 185, image: "https://via.placeholder.com/150?text=Toy15", name: "Playmobil Pirate Ship", description: "Pirate-themed playset with figures, ship, and accessories.", shippingFee: "$5", price: "$45", rating: 5 },
          { id: 186, image: "https://via.placeholder.com/150?text=Toy16", name: "Little Tikes Cozy Coupe", description: "Classic ride-on toy car for toddlers to drive around.", shippingFee: "$10", price: "$60", rating: 5 },
          { id: 187, image: "https://via.placeholder.com/150?text=Toy17", name: "L.O.L. Surprise Doll", description: "Unbox surprise dolls with accessories and outfits.", shippingFee: "$4", price: "$15", rating: 4 },
          { id: 188, image: "https://via.placeholder.com/150?text=Toy18", name: "Slinky", description: "Classic toy that walks down stairs and entertains for hours.", shippingFee: "$2", price: "$6", rating: 4 },
          { id: 189, image: "https://via.placeholder.com/150?text=Toy19", name: "Toy Train Set", description: "Complete toy train set with tracks and engines.", shippingFee: "$8", price: "$50", rating: 5 },
          { id: 280, image: "https://via.placeholder.com/150?text=Toy20", name: "K'NEX Building Set", description: "Build various structures with colorful interlocking pieces.", shippingFee: "$5", price: "$30", rating: 4 }
        ],
      
        furniture: [
          { id: 91, image: "https://via.placeholder.com/150?text=Chair", name: "Eames Lounge Chair", description: "Iconic modern lounge chair with walnut veneer and leather upholstery.", shippingFee: "$30", price: "$1499", rating: 5 },
          { id: 92, image: "https://via.placeholder.com/150?text=Desk", name: "Ikea Linnmon Desk", description: "A spacious, modern desk with a minimalist design.", shippingFee: "$20", price: "$79", rating: 4 },
          { id: 93, image: "https://via.placeholder.com/150?text=Sofa", name: "West Elm Cozy Sofa", description: "Stylish sofa with soft cushions and sleek mid-century legs.", shippingFee: "$50", price: "$1200", rating: 5 },
          { id: 94, image: "https://via.placeholder.com/150?text=Table", name: "CB2 Marble Dining Table", description: "A luxurious dining table with a marble top and metal base.", shippingFee: "$80", price: "$1999", rating: 5 },
          { id: 95, image: "https://via.placeholder.com/150?text=Bookcase", name: "Wayfair Modern Bookcase", description: "A multi-tiered bookcase with a clean, modern aesthetic.", shippingFee: "$30", price: "$150", rating: 4 },
          { id: 96, image: "https://via.placeholder.com/150?text=Bed", name: "Zinus Memory Foam Mattress", description: "Comfortable memory foam mattress for a restful sleep.", shippingFee: "$50", price: "$299", rating: 5 },
          { id: 97, image: "https://via.placeholder.com/150?text=Armchair", name: "Crate & Barrel Leather Armchair", description: "Luxurious leather armchair with a comfortable, supportive design.", shippingFee: "$40", price: "$899", rating: 5 },
          { id: 98, image: "https://via.placeholder.com/150?text=Coffee+Table", name: "Pottery Barn Coffee Table", description: "A rustic coffee table with a wooden surface and steel frame.", shippingFee: "$30", price: "$400", rating: 4 },
          { id: 99, image: "https://via.placeholder.com/150?text=Ottoman", name: "West Elm Velvet Ottoman", description: "Plush velvet ottoman that adds elegance to any room.", shippingFee: "$25", price: "$200", rating: 5 },
          { id: 190, image: "https://via.placeholder.com/150?text=Bookshelf", name: "Ikea Billy Bookcase", description: "Classic 5-shelf bookcase perfect for organizing books and decor.", shippingFee: "$20", price: "$60", rating: 4 },
          { id: 191, image: "https://via.placeholder.com/150?text=TV+Stand", name: "Target TV Stand", description: "Simple, stylish TV stand with open shelving for electronics.", shippingFee: "$30", price: "$180", rating: 4 },
          { id: 192, image: "https://via.placeholder.com/150?text=Dining+Chair", name: "Ashley Furniture Dining Chairs", description: "Elegant dining chairs made from solid wood with a modern finish.", shippingFee: "$20", price: "$90", rating: 5 },
          { id: 193, image: "https://via.placeholder.com/150?text=Side+Table", name: "Wayfair Round Side Table", description: "Compact side table with sleek, minimalist design.", shippingFee: "$15", price: "$50", rating: 4 },
          { id: 194, image: "https://via.placeholder.com/150?text=Dresser", name: "Home Depot 6-Drawer Dresser", description: "Large 6-drawer dresser for extra storage and organization.", shippingFee: "$40", price: "$350", rating: 4 },
          { id: 195, image: "https://via.placeholder.com/150?text=Nightstand", name: "Ikea Hemnes Nightstand", description: "Classic nightstand with a clean design and extra drawer storage.", shippingFee: "$20", price: "$100", rating: 4 },
          { id: 196, image: "https://via.placeholder.com/150?text=Bench", name: "Crate & Barrel Storage Bench", description: "Stylish storage bench with a cushioned top and hidden compartments.", shippingFee: "$30", price: "$250", rating: 5 },
          { id: 197, image: "https://via.placeholder.com/150?text=Lamp", name: "Target Table Lamp", description: "Modern table lamp with a sleek metal base and linen shade.", shippingFee: "$15", price: "$40", rating: 4 },
          { id: 198, image: "https://via.placeholder.com/150?text=Chair", name: "Wayfair Dining Chair", description: "Comfortable dining chair with a solid wood frame.", shippingFee: "$20", price: "$120", rating: 4 },
          { id: 199, image: "https://via.placeholder.com/150?text=Shelf", name: "Ikea Kallax Shelf", description: "Multi-functional shelf unit for storage or display.", shippingFee: "$20", price: "$70", rating: 4 },
          { id: 290, image: "https://via.placeholder.com/150?text=Storage", name: "Home Depot Storage Cabinet", description: "Large storage cabinet with multiple compartments for organizing.", shippingFee: "$40", price: "$350", rating: 4 }
        ],
      

};
  